before:
  hooks:
    - go mod download

builds:
  - id: wireframe
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
  - id: arista
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: wireframe
    package_name: wireframe
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: Nate Sales
    homepage: https://natesales.net/
    maintainer: Nate Sales <nate@natesales.net>
    description: Wireframe is a declarative routing platform integrating BGP with robust filtering support, an XDP dataplane, and VRRP for high availability.
    license: GNU GPL-3.0
    section: utils
    priority: extra
    builds:
      - wireframe

    formats:
      - deb
      - rpm

    recommends:
      - gortr
      - bgpq4
      - bird2

  - id: arista
    package_name: wireframe
    file_name_template: "{{ .ProjectName }}-arista-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: Nate Sales
    homepage: https://natesales.net/
    maintainer: Nate Sales <nate@natesales.net>
    description: Wireframe is a declarative routing platform integrating BGP with robust filtering support, an XDP dataplane, and VRRP for high availability.
    license: GNU GPL-3.0
    section: utils
    priority: extra
    builds:
      - arista
    formats:
      - rpm

publishers:
  - name: fury.io
    ids:
      - wireframe
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/natesales/
