before:
  hooks:
    - go generate
    - go mod download

builds:
  - id: pathvector
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: pathvector
    package_name: pathvector
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: Nate Sales
    homepage: https://pathvector.io
    maintainer: Nate Sales <nate@natesales.net>
    description: Pathvector is a declarative routing control-plane platform for BGP with robust filtering and route optimization
    license: GNU GPL-3.0
    section: utils
    priority: extra
    builds:
      - pathvector

    formats:
      - deb
      - rpm

    recommends:
      - gortr
      - bgpq4
      - bird2

publishers:
  - name: build-arista
    cmd: ./vendorbuild/arista.sh

  - name: fury.io
    ids:
      - pathvector
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/natesales/

release:
  extra_files:
    - glob: arista/pathvector-*-arista-amd64.swix
