ASN = 65530
Router-ID = "192.0.2.1"
PrefSrc4 = "192.0.2.1"
PrefSrc6 = "2001:db8::1"
Prefixes = [
    "192.0.2.0/24",
    "2001:db8::/48"
]

[[VRRP]]
Interface = "eth0"
State = "primary"
VRRID = 1
Priority = 255
VIPs = [
    "192.0.2.1/24",
    "2001:db8::1/48"
]

[Peers."Hurricane Electric"]
ASN = 6939
Type = "upstream"
Neighbors = [
    "203.0.113.39",
    "2001:db8:6939::39"
]

[Peers."Nate Sales"]
ASN = 34553
Type = "peer"
Neighbors = [
    "203.0.113.34",
    "2001:db8:6939::34"
]
