name: Arista build test

on:
  push:
    branches: [ main ]

jobs:
  arista-build:
    name: Arista Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install nfpm
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh

      - name: Move nfpm to /usr/bin/
        run: mv bin/nfpm /usr/bin/nfpm

      - name: make
        run: cd arista && make
