name: go generate

on:
  push:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: go generate
        run: go generate -x

      - name: Commit generated code
        uses: EndBug/add-and-commit@v7
        with:
          message: "ci: go generate"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
