name: Generate and format

on:
  push:

jobs:
  generate-and-format:
    name: Generate and format
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: go generate
        run: go generate -x

      - name: Commit generated code
        uses: EndBug/add-and-commit@v7
        with:
          message: "ci: go generate"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"

      - name: go fmt
        run: go fmt

      - name: Commit formatted code
        uses: EndBug/add-and-commit@v7
        with:
          message: "ci: go fmt"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
