name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Make debian build directory
      run: mkdir -p {debian/DEBIAN/,debian/etc/bcg/,debian/usr/bin/}
    
    - name: Create debian control file
      run: |
        echo "Package: bcg
        Version: 1.0
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Nate Sales <nate@natesales.net>
        Description: The automatic BIRD configuration generator with bogon, IRR, RPKI, and max prefix filtering support." > debian/DEBIAN/control
        
    - name: Create debian copyright file
      run: echo "Copyright 2020 Nathan Sales." > debian/DEBIAN/copyright
    
    - name: Build debian package
      run: dpkg-deb --build debian
    
    - name: List output
      run: ls *.deb

        
        
        
  
