name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install nfpm
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh

      - name: Move nfpm to /usr/bin/
        run: sudo mv bin/nfpm /usr/bin/nfpm

      - run: 'echo $JUNIPER_KEY" > vendorbuild/juniper/key.pem'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.JUNIPER_KEY }}

      - run: 'echo $JUNIPER_CERT" > vendorbuild/juniper/cert.pem'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.JUNIPER_CERT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
