name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install bgpq4 and bird2
        run: |
          wget http://ftp.us.debian.org/debian/pool/main/b/bgpq4/bgpq4_0.0.6-2_amd64.deb
          sudo dpkg -i bgpq4*.deb
          sudo apt install -y bird2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -E gosec

      - name: Get dependencies
        run: go get -v -t -d ./...

      - run: go generate -x
      - run: go build -v .
      - run: make dep
      - run: make test-setup
      - run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

      - run: make test-teardown
