name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install bgpq4 and bird2
        run: |
          sudo add-apt-repository universe --yes
          sudo apt update
          sudo apt install -y bird2 bgpq4

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: go generate
        run: go generate -x

      - name: go build
        run: go build -v .

      - name: go test
        run: go test
