name: SSH

on:
  push:

jobs:
  ssh:
    name: ssh
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16


      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      # - run: mkdir dist && cd dist && bash ../vendorbuild/mikrotik/mtik-build-test.sh
